## Competencia de ciencia de datos 2024 - II

**Nombre completo:**


**Curso:**

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.tree import DecisionTreeClassifier
from sklearn import linear_model
from sklearn.metrics import accuracy_score
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
import warnings
warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',None)

# NOTA: Antes de ejecutar la línea con la que van a generar el csv de predicciones NO OLVIDEN
# que deben devolver la variable objetivo a tipo booleano. Usen la siguiente estructura:
# nombre_df_predicciones.Transported = nombre_df_predicciones.Transported.map({1:True,0:False})

In [5]:
# Leer datos del archivo con etiquetas
train = pd.read_csv('nombre_archivo')
train['dataset'] = 'train'
# Leer datos del archivo de predicción (sin etiquetas)
pred = pd.read_csv('nombre_archivo')
pred['dataset'] = 'pred'
data = pd.concat([train,pred]).reset_index(drop=True)
data.Transported = data.Transported.map({True:1,False:0})
data.set_index('PassengerId',inplace=True)
data.head(1)

,HomePlanet,CryoSleep,Cabin,Destination,Age,VIP,RoomService,FoodCourt,ShoppingMall,Spa,VRDeck,Name,Transported,dataset
PassengerId,,,,,,,,,,,,,,
0001_01,Europa,False,B/0/P,TRAPPIST-1e,39.0,False,0.0,0.0,0.0,0.0,0.0,Maham Ofracculy,0.0,train

In [ ]:
# Función para limpiar outliers
def reemplazar_outliers(dataframe, columna, metodo='mediana'):
    df = dataframe.copy()
    Q1 = df[columna].quantile(0.25)
    Q3 = df[columna].quantile(0.75)
    IQR = Q3 - Q1
    limite_inferior = Q1 - 1.5 * IQR
    limite_superior = Q3 + 1.5 * IQR
    if metodo == 'mediana':
        mediana = df[columna].median()
        df[columna] = np.where((df[columna] < limite_inferior) | (df[columna] > limite_superior), mediana, df[columna])
    elif metodo == 'media':
        media = df[columna].mean()
        df[columna] = np.where((df[columna] < limite_inferior) | (df[columna] > limite_superior), media, df[columna])
    elif metodo == 'bigotes':
        df[columna] = np.where((df[columna] < limite_inferior), limite_inferior, df[columna])
        df[columna] = np.where((df[columna] > limite_superior), limite_superior, df[columna])
    return df